"""добавил фото

Revision ID: 04cc00785fb3
Revises: d9c245ddc050
Create Date: 2024-05-25 22:47:05.903303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04cc00785fb3'
down_revision: Union[str, None] = 'd9c245ddc050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('photo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'photo')
    # ### end Alembic commands ###
