"""исправил связи

Revision ID: 3ffa7429f7fc
Revises: 2d1f1a43ddfc
Create Date: 2024-05-25 20:15:39.626987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffa7429f7fc'
down_revision: Union[str, None] = '2d1f1a43ddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('brands_category_fkey', 'brands', type_='foreignkey')
    op.create_foreign_key(None, 'brands', 'categories', ['category_id'], ['id'])
    op.drop_column('brands', 'category')
    op.add_column('items', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.drop_constraint('items_brand_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'brands', ['brand_id'], ['id'])
    op.drop_column('items', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('brand', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_brand_fkey', 'items', 'brands', ['brand'], ['id'])
    op.drop_column('items', 'brand_id')
    op.add_column('brands', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.create_foreign_key('brands_category_fkey', 'brands', 'categories', ['category'], ['id'])
    op.drop_column('brands', 'category_id')
    # ### end Alembic commands ###
