"""исправил связи

Revision ID: d9c245ddc050
Revises: 3ffa7429f7fc
Create Date: 2024-05-25 20:19:50.734651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c245ddc050'
down_revision: Union[str, None] = '3ffa7429f7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('brands_category_id_fkey', 'brands', type_='foreignkey')
    op.create_foreign_key(None, 'brands', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('items_brand_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_brand_id_fkey', 'items', 'brands', ['brand_id'], ['id'])
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.create_foreign_key('brands_category_id_fkey', 'brands', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
